### ISSUE TITLE
Scale bug take 2

### ISSUE THREAD

**Issue by redvex** [KieranLafferty/KLNoteViewController#21] opened 2013-03-23 07:35 UTC
I've update KLNoteViewController on my project with the last version (Bug fixed for https://github.com/KieranLafferty/KLNoteViewController/pull/16).

It's pixel perfect on portrait, it's still buggy on landscape:
![Schermata 2013-03-23 alle 08 11 37](https://f.cloud.github.com/assets/114123/293587/e91e714e-9389-11e2-8c33-a72f9de6c97b.png)
~140px from status bar to first view bar
![Schermata 2013-03-23 alle 08 11 44](https://f.cloud.github.com/assets/114123/293588/e925a068-9389-11e2-89d4-b1be6cdc7c8b.png)
~190px from status bar to first view bar

This is my conf:
**#define kDefaultMinimizedScalingFactor 1.00**
# define kDefaultMaximizedScalingFactor 1.00
# define kDefaultNavigationBarOverlap 0.90
# define kDefaultAnimationDuration 0.3
# define kDefaultReloadHideAnimationDuration 0.4
# define kDefaultReloadShowAnimationDuration 0.6

**#define kDefaultVerticalOrigin 250**
# define kDefaultCornerRadius 5.0
# define kDefaultShadowEnabled YES
# define kDefaultShadowColor [UIColor blackColor]
# define kDefaultShadowOffset CGSizeMake(0, -5)
# define kDefaultShadowRadius kDefaultCornerRadius
# define kDefaultShadowOpacity 0.60
# define kDefaultMinimumPressDuration 0.2

With default values this issue is still present (only in landscape) but is less visible even if after some rotation some defects are still present:

![Schermata 2013-03-23 alle 08 28 52](https://f.cloud.github.com/assets/114123/293598/f8351c6c-938b-11e2-828d-2e4f68611351.png)

That's all :)

**Comment by KieranLafferty** [comment] 2013-03-31 18:23
Hey Redvex, thanks for bringing this up. Currently this control is only supported in portrait orientation (see README). It is clear that this should be adapted to work on landscape as well, but at the moment I have been short on time to implement this fix. 

Keep the bug reports coming though, very much appreciated :)

**Comment by chintan100** [comment] 2013-06-08 18:38
Hi, 

I am able to reproduce this issue in portrait on iPhone 4S running iOS 6.1.3. 
![bug](https://f.cloud.github.com/assets/1689870/627950/430d0fc2-d06a-11e2-8c44-c2c01dca1e35.png)

Let me know if you are working on this fix now or can guide me in right direction. It is very difficult to reproduce but random taps and pans makes it happen sometimes.

**Comment by KieranLafferty** [comment] 2013-06-09 23:20
Hey Chintan,

I have seen several reports of this type of behaviour, however for all cases reported thus far have had to do with people using it for both portrait and landscape where the action of turning from one to the other (portrait -> landscape and vice versa) is causing this issue. As mentioned in the readme this control supports only portrait, meaning that if your app allows for orientation changes then it will immediately mess with the control in unexpected ways. I will close this for now but feel free to let me know if you are getting this behaviour with only portrait mode enabled

**Closed as completed by KieranLafferty** 2013-06-09 23:20 UTC

**Comment by chintan100** [comment] 2013-06-11 10:46
Yes, disabling landscape orientations does fix the issue. Thank you for this control and keep up the good work!

**Comment by raheelahmad786** [comment] 2016-02-19 08:26
@chintan100
 How did you disable the landscape orientation in KNoteViewController ? Can you please mention ?

Thanks.

**Comment by chintan100** [comment] 2016-02-19 08:42
I don't remember since it was a while back but i think i just disabled landscape orientation from Target settings in Xcode.
